name: PHPUnit

on:
  push:
    branches: [ master, main ]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  test-phpunit:
    name: PHPUnit (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-20.04 ]
        php-versions: [ '7.4', '8.0', '8.1' ]
        phpunit-versions: [ '9.5' ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit:${{ matrix.phpunit-versions }}

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: make install

      - name: Run test suite
        run: make test

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
